/**
 * Extra CC0 catalog slots from official Kenney / Quaternius / Poly Haven packs.
 * Metadata only — binaries stay opt-in via ingest download.
 */
import type { AssetCategory, AssetKind, CatalogAsset } from "./types.js";

type Row = [id: string, name: string, category: AssetCategory, ...tags: string[]];

export function kenneyPack(
  packId: string,
  pageSlug: string,
  kind: AssetKind,
  rows: Row[],
  extra?: { uploadSupported?: boolean },
): CatalogAsset[] {
  return rows.map(([id, name, category, ...tags]) => ({
    id,
    name,
    category,
    kind,
    tags: [...tags, packId],
    license: "CC0",
    attribution: "Kenney (https://kenney.nl) — CC0 1.0",
    source: `https://kenney.nl/assets/${pageSlug}`,
    packId,
    uploadSupported: extra?.uploadSupported ?? kind !== "audio",
  }));
}

export function quatPack(rows: Row[]): CatalogAsset[] {
  return rows.map(([id, name, category, ...tags]) => ({
    id,
    name,
    category,
    kind: "model",
    tags,
    license: "CC0",
    attribution: "Quaternius (https://quaternius.com) — CC0 1.0",
    source: "https://quaternius.com",
    packId: "quaternius-cc0",
    uploadSupported: true,
  }));
}

export function polyHavenTexture(
  slug: string,
  name: string,
  tags: string[],
): CatalogAsset {
  return {
    id: `ph_${slug}`,
    name,
    category: "texture",
    kind: "texture",
    tags: [...tags, "pbr", "polyhaven"],
    license: "CC0",
    attribution: "Poly Haven (https://polyhaven.com) — CC0 1.0",
    source: `https://polyhaven.com/a/${slug}`,
    packId: "polyhaven-cc0",
    downloadUrl: `https://dl.polyhaven.org/file/ph-assets/Textures/png/1k/${slug}/${slug}_diff_1k.png`,
    uploadSupported: true,
  };
}

export function polyHavenHdri(slug: string, name: string, tags: string[]): CatalogAsset {
  return {
    id: `ph_hdri_${slug}`,
    name,
    category: "texture",
    kind: "hdri",
    tags: [...tags, "hdri", "polyhaven"],
    license: "CC0",
    attribution: "Poly Haven (https://polyhaven.com) — CC0 1.0",
    source: `https://polyhaven.com/a/${slug}`,
    packId: "polyhaven-cc0",
    uploadSupported: false,
  };
}

export function polyHavenModel(
  slug: string,
  name: string,
  category: AssetCategory,
  tags: string[],
): CatalogAsset {
  return {
    id: `ph_model_${slug}`,
    name,
    category,
    kind: "model",
    tags: [...tags, "polyhaven", "model"],
    license: "CC0",
    attribution: "Poly Haven (https://polyhaven.com) — CC0 1.0",
    source: `https://polyhaven.com/a/${slug}`,
    packId: "polyhaven-cc0",
    uploadSupported: true,
  };
}

export const KENNEY_PACK_ASSETS: CatalogAsset[] = [
  ...kenneyPack("nature-kit", "nature-kit", "model", [
    ["kenney_nat_pine", "Pine Tree", "environment", "tree", "pine", "nature"],
    ["kenney_nat_birch", "Birch Tree", "environment", "tree", "birch", "nature"],
    ["kenney_nat_dead_tree", "Dead Tree", "environment", "tree", "dead"],
    ["kenney_nat_stump", "Tree Stump", "environment", "stump", "wood"],
    ["kenney_nat_log", "Fallen Log", "environment", "log", "wood"],
    ["kenney_nat_cliff", "Cliff", "environment", "cliff", "rock"],
    ["kenney_nat_boulder", "Boulder", "environment", "rock", "boulder"],
    ["kenney_nat_fern", "Fern", "environment", "fern", "plant"],
    ["kenney_nat_flower_yellow", "Yellow Flower", "environment", "flower"],
    ["kenney_nat_cactus", "Cactus", "environment", "cactus", "desert"],
    ["kenney_nat_lily", "Lily Pad", "environment", "water", "plant"],
    ["kenney_nat_reed", "Reed", "environment", "water", "plant"],
    ["kenney_nat_snow_pine", "Snow Pine", "environment", "tree", "snow"],
    ["kenney_nat_ice_block", "Ice Block", "environment", "ice", "obby"],
    ["kenney_nat_hedge", "Hedge", "environment", "hedge", "plant"],
  ]),
  ...kenneyPack("food-kit", "food-kit", "model", [
    ["kenney_food_apple", "Apple", "prop", "food", "fruit"],
    ["kenney_food_banana", "Banana", "prop", "food", "fruit"],
    ["kenney_food_burger", "Burger", "prop", "food", "meal"],
    ["kenney_food_pizza", "Pizza", "prop", "food", "meal"],
    ["kenney_food_donut", "Donut", "prop", "food", "sweet"],
    ["kenney_food_icecream", "Ice Cream", "prop", "food", "sweet"],
    ["kenney_food_sushi", "Sushi", "prop", "food", "meal"],
    ["kenney_food_taco", "Taco", "prop", "food", "meal"],
    ["kenney_food_cake", "Cake", "prop", "food", "sweet"],
    ["kenney_food_coffee", "Coffee Cup", "prop", "food", "drink"],
    ["kenney_food_soda", "Soda Can", "prop", "food", "drink"],
    ["kenney_food_bread", "Bread", "prop", "food", "bakery"],
    ["kenney_food_cheese", "Cheese", "prop", "food"],
    ["kenney_food_steak", "Steak", "prop", "food", "meal"],
    ["kenney_food_carrot", "Carrot", "prop", "food", "veg"],
    ["kenney_food_fish", "Fish", "prop", "food", "seafood"],
  ]),
  ...kenneyPack("furniture-kit", "furniture-kit", "model", [
    ["kenney_furn_sofa", "Sofa", "prop", "furniture", "living"],
    ["kenney_furn_lamp", "Floor Lamp", "prop", "furniture", "light"],
    ["kenney_furn_tv", "Television", "prop", "furniture", "living"],
    ["kenney_furn_fridge", "Fridge", "prop", "furniture", "kitchen"],
    ["kenney_furn_stove", "Stove", "prop", "furniture", "kitchen"],
    ["kenney_furn_sink", "Sink", "prop", "furniture", "kitchen"],
    ["kenney_furn_toilet", "Toilet", "prop", "furniture", "bath"],
    ["kenney_furn_bathtub", "Bathtub", "prop", "furniture", "bath"],
    ["kenney_furn_wardrobe", "Wardrobe", "prop", "furniture"],
    ["kenney_furn_desk", "Desk", "prop", "furniture", "office"],
    ["kenney_furn_nightstand", "Nightstand", "prop", "furniture"],
    ["kenney_furn_plantpot", "Potted Plant", "prop", "furniture", "plant"],
    ["kenney_furn_microwave", "Microwave", "prop", "furniture", "kitchen"],
    ["kenney_furn_washer", "Washing Machine", "prop", "furniture"],
    ["kenney_furn_counter", "Kitchen Counter", "prop", "furniture", "kitchen"],
  ]),
  ...kenneyPack("castle-kit", "castle-kit", "model", [
    ["kenney_castle_wall", "Castle Wall", "environment", "castle", "wall"],
    ["kenney_castle_keep", "Keep", "environment", "castle", "building"],
    ["kenney_castle_battlement", "Battlement", "environment", "castle"],
    ["kenney_castle_gatehouse", "Gatehouse", "environment", "castle", "gate"],
    ["kenney_castle_banner", "Castle Banner", "prop", "castle", "flag"],
    ["kenney_castle_throne", "Throne", "prop", "castle", "furniture"],
    ["kenney_castle_catapult", "Catapult", "prop", "castle", "siege"],
    ["kenney_castle_battering_ram", "Battering Ram", "prop", "castle", "siege"],
    ["kenney_castle_dungeon_door", "Dungeon Door", "prop", "castle", "door"],
    ["kenney_castle_arrow_slit", "Arrow Slit Wall", "environment", "castle"],
  ]),
  ...kenneyPack("platformer-kit", "platformer-kit", "model", [
    ["kenney_plat_grass_block", "Grass Block", "environment", "obby", "block"],
    ["kenney_plat_question", "Question Block", "prop", "obby", "block"],
    ["kenney_plat_pipe", "Pipe", "environment", "obby", "pipe"],
    ["kenney_plat_spring", "Spring", "prop", "obby", "bounce"],
    ["kenney_plat_moving", "Moving Platform", "environment", "obby", "platform"],
    ["kenney_plat_goal", "Goal Flag", "prop", "obby", "checkpoint"],
    ["kenney_plat_coin_block", "Coin Block", "prop", "obby", "coin"],
    ["kenney_plat_ladder_block", "Climb Block", "environment", "obby"],
    ["kenney_plat_ice_block", "Ice Platform", "environment", "obby", "ice"],
    ["kenney_plat_lava", "Lava Hazard", "prop", "obby", "hazard"],
  ]),
  ...kenneyPack("space-kit", "space-kit", "model", [
    ["kenney_space_satellite", "Satellite", "prop", "space"],
    ["kenney_space_rover", "Rover", "prop", "space", "vehicle"],
    ["kenney_space_asteroid", "Asteroid", "environment", "space"],
    ["kenney_space_astronaut", "Astronaut", "character", "space", "npc"],
    ["kenney_space_hangar", "Hangar", "environment", "space", "building"],
    ["kenney_space_solar", "Solar Panel", "prop", "space"],
    ["kenney_space_crate", "Metal Crate", "prop", "space", "crate"],
    ["kenney_space_turret", "Turret", "prop", "space", "weapon"],
    ["kenney_space_ufo", "UFO", "prop", "space", "vehicle"],
    ["kenney_space_station_mod", "Station Module", "environment", "space"],
  ]),
  ...kenneyPack("city-kit-industrial", "city-kit-industrial", "model", [
    ["kenney_city_warehouse", "Warehouse", "environment", "city", "building"],
    ["kenney_city_silo", "Silo", "environment", "city", "building"],
    ["kenney_city_crane", "Crane", "prop", "city", "industrial"],
    ["kenney_city_pallet", "Pallet", "prop", "city", "crate"],
    ["kenney_city_dumpster", "Dumpster", "prop", "city"],
    ["kenney_city_cone", "Traffic Cone", "prop", "city", "hazard"],
    ["kenney_city_hydrant", "Fire Hydrant", "prop", "city"],
    ["kenney_city_streetlamp", "Street Lamp", "prop", "city", "light"],
    ["kenney_city_bus_stop", "Bus Stop", "environment", "city"],
    ["kenney_city_barrier", "Road Barrier", "prop", "city"],
  ]),
  ...kenneyPack("city-kit-roads", "city-kit-roads", "model", [
    ["kenney_road_straight", "Road Straight", "environment", "city", "road"],
    ["kenney_road_corner", "Road Corner", "environment", "city", "road"],
    ["kenney_road_crossing", "Crosswalk", "environment", "city", "road"],
    ["kenney_road_roundabout", "Roundabout", "environment", "city", "road"],
    ["kenney_road_parking", "Parking Stall", "environment", "city", "road"],
  ]),
  ...kenneyPack("pirate-kit", "pirate-kit", "model", [
    ["kenney_pirate_ship", "Pirate Ship", "prop", "pirate", "vehicle"],
    ["kenney_pirate_cannon", "Cannon", "prop", "pirate", "weapon"],
    ["kenney_pirate_palm", "Palm Tree", "environment", "pirate", "tree"],
    ["kenney_pirate_dock", "Dock", "environment", "pirate"],
    ["kenney_pirate_anchor", "Anchor", "prop", "pirate"],
    ["kenney_pirate_helm", "Ship Helm", "prop", "pirate"],
    ["kenney_pirate_island", "Island Rock", "environment", "pirate"],
  ]),
  ...kenneyPack("western-kit", "western-kit", "model", [
    ["kenney_west_saloon", "Saloon", "environment", "western", "building"],
    ["kenney_west_wagon", "Wagon", "prop", "western", "vehicle"],
    ["kenney_west_trough", "Water Trough", "prop", "western"],
    ["kenney_west_windmill", "Windmill", "environment", "western", "building"],
    ["kenney_west_rail", "Railroad Track", "environment", "western"],
    ["kenney_west_wanted", "Wanted Poster", "prop", "western", "sign"],
  ]),
  ...kenneyPack("mini-dungeon", "mini-dungeon", "model", [
    ["kenney_dung_altar", "Altar", "prop", "dungeon"],
    ["kenney_dung_trap_floor", "Trap Floor", "prop", "dungeon", "hazard"],
    ["kenney_dung_shelf", "Potion Shelf", "prop", "dungeon"],
    ["kenney_dung_bones", "Bone Pile", "prop", "dungeon", "undead"],
    ["kenney_dung_pentacle", "Pentacle Floor", "environment", "dungeon"],
    ["kenney_dung_pillar", "Dungeon Pillar", "environment", "dungeon"],
  ]),
  ...kenneyPack("modular-cave-kit", "modular-cave-kit", "model", [
    ["kenney_cave_crystal", "Crystal", "prop", "cave", "ore"],
    ["kenney_cave_stalagmite", "Stalagmite", "environment", "cave"],
    ["kenney_cave_stalactite", "Stalactite", "environment", "cave"],
    ["kenney_cave_ore", "Ore Node", "prop", "cave", "ore"],
    ["kenney_cave_rails", "Mine Rails", "environment", "cave"],
    ["kenney_cave_cart", "Minecart", "prop", "cave", "vehicle"],
  ]),
  ...kenneyPack("car-kit", "car-kit", "model", [
    ["kenney_veh_sedan", "Sedan", "prop", "vehicle", "car"],
    ["kenney_veh_sports", "Sports Car", "prop", "vehicle", "car"],
    ["kenney_veh_police", "Police Car", "prop", "vehicle", "car"],
    ["kenney_veh_taxi", "Taxi", "prop", "vehicle", "car"],
    ["kenney_veh_bus", "Bus", "prop", "vehicle"],
    ["kenney_veh_ambulance", "Ambulance", "prop", "vehicle"],
    ["kenney_veh_motorcycle", "Motorcycle", "prop", "vehicle"],
    ["kenney_veh_tractor", "Tractor", "prop", "vehicle", "farm"],
    ["kenney_veh_forklift", "Forklift", "prop", "vehicle", "industrial"],
  ]),
  ...kenneyPack("animal-pack-remastered", "animal-pack-remastered", "model", [
    ["kenney_animal_cat", "Cat", "character", "animal"],
    ["kenney_animal_dog", "Dog", "character", "animal"],
    ["kenney_animal_bird", "Bird", "character", "animal"],
    ["kenney_animal_horse", "Horse", "character", "animal"],
    ["kenney_animal_cow", "Cow", "character", "animal", "farm"],
    ["kenney_animal_pig", "Pig", "character", "animal", "farm"],
    ["kenney_animal_chicken", "Chicken", "character", "animal", "farm"],
    ["kenney_animal_sheep", "Sheep", "character", "animal", "farm"],
    ["kenney_animal_wolf", "Wolf", "character", "animal", "enemy"],
  ]),
  ...kenneyPack("graveyard-kit", "graveyard-kit", "model", [
    ["kenney_grave_tombstone", "Tombstone", "prop", "graveyard"],
    ["kenney_grave_coffin", "Coffin", "prop", "graveyard"],
    ["kenney_grave_crypt", "Crypt", "environment", "graveyard", "building"],
    ["kenney_grave_iron_gate", "Iron Gate", "environment", "graveyard"],
    ["kenney_grave_candle", "Grave Candle", "prop", "graveyard", "light"],
  ]),
  ...kenneyPack("holiday-kit", "holiday-kit", "model", [
    ["kenney_holi_pumpkin", "Pumpkin", "prop", "holiday"],
    ["kenney_holi_gift", "Gift Box", "prop", "holiday"],
    ["kenney_holi_tree", "Holiday Tree", "environment", "holiday", "tree"],
    ["kenney_holi_snowman", "Snowman", "prop", "holiday", "snow"],
    ["kenney_holi_wreath", "Wreath", "prop", "holiday"],
    ["kenney_holi_balloon", "Balloon", "prop", "holiday"],
  ]),
  ...kenneyPack("ui-pack", "ui-pack", "image", [
    ["kenney_ui_icon_map", "Icon Map", "ui", "icon", "map"],
    ["kenney_ui_icon_quest", "Icon Quest", "ui", "icon", "quest"],
    ["kenney_ui_icon_shop", "Icon Shop", "ui", "icon", "shop"],
    ["kenney_ui_icon_bag", "Icon Bag", "ui", "icon", "inventory"],
    ["kenney_ui_icon_sword", "Icon Sword", "ui", "icon", "combat"],
    ["kenney_ui_icon_potion", "Icon Potion", "ui", "icon", "item"],
    ["kenney_ui_icon_lock", "Icon Lock", "ui", "icon", "lock"],
    ["kenney_ui_icon_chat", "Icon Chat", "ui", "icon", "social"],
    ["kenney_ui_icon_crown", "Icon Crown", "ui", "icon", "rank"],
    ["kenney_ui_icon_energy", "Icon Energy", "ui", "icon", "stat"],
    ["kenney_ui_icon_ticket", "Icon Ticket", "ui", "icon", "currency"],
    ["kenney_ui_icon_check", "Icon Check", "ui", "icon"],
    ["kenney_ui_icon_close", "Icon Close", "ui", "icon"],
    ["kenney_ui_frame_gold", "Gold Frame", "ui", "frame"],
    ["kenney_ui_slot", "Inventory Slot", "ui", "slot"],
  ]),
  ...kenneyPack("input-prompts", "input-prompts", "image", [
    ["kenney_prompt_e", "Prompt E", "ui", "prompt", "keyboard"],
    ["kenney_prompt_f", "Prompt F", "ui", "prompt", "keyboard"],
    ["kenney_prompt_space", "Prompt Space", "ui", "prompt", "keyboard"],
    ["kenney_prompt_click", "Prompt Click", "ui", "prompt", "mouse"],
  ]),
  ...kenneyPack(
    "impact-sounds",
    "impact-sounds",
    "audio",
    [
      ["kenney_sfx_footstep", "Footstep", "audio", "foley"],
      ["kenney_sfx_door", "Door", "audio", "foley"],
      ["kenney_sfx_whoosh", "Whoosh", "audio", "combat"],
      ["kenney_sfx_magic", "Magic Cast", "audio", "magic"],
      ["kenney_sfx_levelup", "Level Up", "audio", "ui"],
      ["kenney_sfx_heal", "Heal", "audio", "magic"],
      ["kenney_sfx_damage", "Damage", "audio", "combat"],
      ["kenney_sfx_ui_hover", "UI Hover", "audio", "ui"],
      ["kenney_sfx_ui_error", "UI Error", "audio", "ui"],
      ["kenney_sfx_ui_ok", "UI Success", "audio", "ui"],
    ],
    { uploadSupported: false },
  ),
  ...kenneyPack(
    "rpg-audio",
    "rpg-audio",
    "audio",
    [
      ["kenney_music_shop", "Shop Loop", "audio", "music"],
      ["kenney_music_night", "Night Loop", "audio", "music"],
      ["kenney_music_town", "Town Loop", "audio", "music"],
      ["kenney_amb_forest", "Forest Ambience", "audio", "ambient"],
      ["kenney_amb_cave", "Cave Ambience", "audio", "ambient"],
      ["kenney_amb_town", "Town Ambience", "audio", "ambient"],
    ],
    { uploadSupported: false },
  ),
];

export const QUATERNIUS_PACK_ASSETS: CatalogAsset[] = quatPack([
  ["quat_fox", "Fox", "character", "animal"],
  ["quat_deer", "Deer", "character", "animal"],
  ["quat_wolf", "Wolf", "character", "animal", "enemy"],
  ["quat_bird", "Bird", "character", "animal"],
  ["quat_car_sedan", "Sedan", "prop", "vehicle", "car"],
  ["quat_bike", "Bicycle", "prop", "vehicle"],
  ["quat_food_burger", "Burger", "prop", "food"],
  ["quat_food_pizza", "Pizza", "prop", "food"],
  ["quat_food_apple", "Apple", "prop", "food"],
  ["quat_mod_wall", "Modular Wall", "environment", "modular", "building"],
  ["quat_mod_floor", "Modular Floor", "environment", "modular"],
  ["quat_mod_roof", "Modular Roof", "environment", "modular", "building"],
  ["quat_mod_window", "Modular Window", "environment", "modular"],
  ["quat_mod_door", "Modular Door", "prop", "modular", "door"],
  ["quat_slime", "Slime", "character", "enemy"],
  ["quat_bat", "Bat", "character", "enemy", "animal"],
  ["quat_spider", "Spider", "character", "enemy"],
  ["quat_coin", "Coin", "prop", "currency"],
  ["quat_spring", "Spring", "prop", "obby"],
  ["quat_flag", "Flag", "prop", "checkpoint"],
  ["quat_chest", "Chest", "prop", "loot"],
  ["quat_sword", "Sword", "prop", "weapon"],
  ["quat_shield", "Shield", "prop", "armor"],
]);

export const POLY_HAVEN_PACK_ASSETS: CatalogAsset[] = [
  polyHavenTexture("plywood", "Plywood", ["wood", "indoor"]),
  polyHavenTexture("coast_sand_rocks_02", "Coast Sand Rocks", ["sand", "terrain", "outdoor"]),
  polyHavenTexture("brown_mud_leaves_01", "Mud Leaves", ["dirt", "terrain", "outdoor"]),
  polyHavenTexture("laminate_floor_02", "Laminate Floor", ["floor", "wood", "indoor"]),
  polyHavenTexture("wood_table_001", "Wood Table", ["wood", "indoor"]),
  polyHavenTexture("concrete_floor_worn_001", "Worn Concrete Floor", ["concrete", "floor"]),
  polyHavenTexture("oak_veneer_01", "Oak Veneer", ["wood"]),
  polyHavenTexture("beige_wall_001", "Beige Wall", ["wall", "plaster"]),
  polyHavenTexture("aerial_rocks_02", "Aerial Rocks", ["rock", "terrain"]),
  polyHavenTexture("asphalt_02", "Asphalt", ["road", "city"]),
  polyHavenTexture("aerial_grass_rock", "Aerial Grass Rock", ["grass", "terrain"]),
  polyHavenTexture("fabric_pattern_07", "Fabric Pattern", ["fabric"]),
  polyHavenTexture("forrest_ground_01", "Forest Ground", ["dirt", "outdoor"]),
  polyHavenTexture("marble_01", "Marble", ["floor", "indoor"]),
  polyHavenTexture("painted_plaster_wall", "Painted Plaster", ["wall"]),
  polyHavenTexture("weathered_brown_planks", "Weathered Planks", ["wood", "outdoor"]),
  polyHavenTexture("green_metal_rust", "Rusted Green Metal", ["metal"]),
  polyHavenTexture("snow_02", "Snow", ["snow", "terrain"]),
  polyHavenTexture("white_plaster_02", "White Plaster", ["wall"]),
  polyHavenTexture("rough_wood", "Rough Wood", ["wood", "outdoor"]),
  polyHavenTexture("dark_wood", "Dark Wood", ["wood", "indoor"]),
  polyHavenTexture("rusty_metal_02", "Rusty Metal", ["metal"]),
  polyHavenTexture("brown_leather", "Brown Leather", ["fabric", "leather"]),
  polyHavenTexture("concrete_floor_02", "Concrete Floor", ["concrete"]),
  polyHavenTexture("rock_face_03", "Rock Face", ["rock", "cliff"]),
  polyHavenTexture("red_brick", "Red Brick", ["brick", "wall"]),
  polyHavenHdri("venice_sunset", "Venice Sunset HDRI (preview)", ["sky", "sunset"]),
  polyHavenHdri("klaas", "Klaas Studio HDRI (preview)", ["studio"]),
  polyHavenHdri("forest_slope", "Forest Slope HDRI (preview)", ["forest", "outdoor"]),
  polyHavenHdri("studio_small_03", "Small Studio HDRI (preview)", ["studio"]),
  polyHavenHdri("moonless_golf", "Moonless Night HDRI (preview)", ["night", "sky"]),
  polyHavenHdri("dam_wall", "Dam Wall HDRI (preview)", ["outdoor"]),
];
