/**
 * Deep CC0 catalog expansion from Kenney's live pack index (215 packs,
 * /assets/page:1–14), extra Quaternius kits, and top Poly Haven downloads.
 * Unique ids only — not dummy _vN copies.
 */
import type { CatalogAsset } from "./types.js";
import {
  kenneyPack,
  polyHavenHdri,
  polyHavenModel,
  polyHavenTexture,
  quatPack,
} from "./seed-packs.js";

export const KENNEY_DEEP_ASSETS: CatalogAsset[] = [
  ...kenneyPack("factory-kit", "factory-kit", "model", [
    ["kenney_fact_conveyor", "Conveyor Belt", "environment", "factory", "machine"],
    ["kenney_fact_robot_arm", "Robot Arm", "prop", "factory", "machine"],
    ["kenney_fact_pipe", "Factory Pipe", "environment", "factory"],
    ["kenney_fact_tank", "Storage Tank", "environment", "factory"],
    ["kenney_fact_smokestack", "Smokestack", "environment", "factory"],
    ["kenney_fact_gear", "Giant Gear", "prop", "factory"],
    ["kenney_fact_control", "Control Panel", "prop", "factory"],
    ["kenney_fact_crate_metal", "Metal Crate", "prop", "factory", "crate"],
    ["kenney_fact_warning", "Warning Sign", "prop", "factory", "sign"],
    ["kenney_fact_floor", "Factory Floor Tile", "environment", "factory"],
  ]),
  ...kenneyPack("fantasy-town-kit", "fantasy-town-kit", "model", [
    ["kenney_ftown_inn", "Inn", "environment", "fantasy", "building"],
    ["kenney_ftown_shop", "Shop Stall", "environment", "fantasy", "building"],
    ["kenney_ftown_blacksmith", "Blacksmith", "environment", "fantasy", "building"],
    ["kenney_ftown_windmill", "Town Windmill", "environment", "fantasy", "building"],
    ["kenney_ftown_well", "Town Well", "environment", "fantasy"],
    ["kenney_ftown_market", "Market Stall", "prop", "fantasy"],
    ["kenney_ftown_wagon", "Merchant Wagon", "prop", "fantasy", "vehicle"],
    ["kenney_ftown_banner", "Town Banner", "prop", "fantasy", "flag"],
    ["kenney_ftown_lantern", "Street Lantern", "prop", "fantasy", "light"],
    ["kenney_ftown_roof", "Tiled Roof", "environment", "fantasy", "building"],
  ]),
  ...kenneyPack("city-kit-commercial", "city-kit-commercial", "model", [
    ["kenney_cityc_shop", "Shop Building", "environment", "city", "building"],
    ["kenney_cityc_mall", "Mall Block", "environment", "city", "building"],
    ["kenney_cityc_office", "Office Tower", "environment", "city", "building"],
    ["kenney_cityc_cafe", "Cafe", "environment", "city", "building"],
    ["kenney_cityc_sign", "Neon Sign", "prop", "city", "sign"],
    ["kenney_cityc_awning", "Store Awning", "prop", "city"],
    ["kenney_cityc_bench", "City Bench", "prop", "city", "furniture"],
    ["kenney_cityc_bin", "Trash Bin", "prop", "city"],
  ]),
  ...kenneyPack("city-kit-suburban", "city-kit-suburban", "model", [
    ["kenney_citys_house", "Suburban House", "environment", "city", "building"],
    ["kenney_citys_garage", "Garage", "environment", "city", "building"],
    ["kenney_citys_driveway", "Driveway", "environment", "city"],
    ["kenney_citys_mailbox", "Mailbox", "prop", "city"],
    ["kenney_citys_hedge", "Suburban Hedge", "environment", "city", "plant"],
    ["kenney_citys_pool", "Swimming Pool", "environment", "city"],
    ["kenney_citys_slide", "Playground Slide", "prop", "city"],
    ["kenney_citys_fence", "Picket Fence", "environment", "city"],
  ]),
  ...kenneyPack("space-station-kit", "space-station-kit", "model", [
    ["kenney_stn_corridor", "Station Corridor", "environment", "space", "modular"],
    ["kenney_stn_airlock", "Airlock", "environment", "space"],
    ["kenney_stn_console", "Station Console", "prop", "space"],
    ["kenney_stn_bed", "Crew Bed", "prop", "space", "furniture"],
    ["kenney_stn_window", "Space Window", "environment", "space"],
    ["kenney_stn_reactor", "Reactor Core", "prop", "space"],
    ["kenney_stn_dock", "Docking Port", "environment", "space"],
    ["kenney_stn_chair", "Pilot Chair", "prop", "space", "furniture"],
  ]),
  ...kenneyPack("modular-space-kit", "modular-space-kit", "model", [
    ["kenney_mspace_floor", "Space Floor", "environment", "space", "modular"],
    ["kenney_mspace_wall", "Space Wall", "environment", "space", "modular"],
    ["kenney_mspace_corner", "Space Corner", "environment", "space", "modular"],
    ["kenney_mspace_door", "Space Door", "prop", "space", "door"],
    ["kenney_mspace_pillar", "Space Pillar", "environment", "space", "modular"],
    ["kenney_mspace_ramp", "Space Ramp", "environment", "space", "obby"],
  ]),
  ...kenneyPack("modular-dungeon-kit", "modular-dungeon-kit", "model", [
    ["kenney_mdung_wall", "Dungeon Wall", "environment", "dungeon", "modular"],
    ["kenney_mdung_floor", "Dungeon Floor", "environment", "dungeon", "modular"],
    ["kenney_mdung_stairs", "Dungeon Stairs", "environment", "dungeon"],
    ["kenney_mdung_arch", "Dungeon Arch", "environment", "dungeon"],
    ["kenney_mdung_trap", "Spike Trap Tile", "prop", "dungeon", "hazard"],
    ["kenney_mdung_chest", "Dungeon Chest", "prop", "dungeon", "loot"],
    ["kenney_mdung_torch", "Wall Torch", "prop", "dungeon", "light"],
    ["kenney_mdung_bars", "Jail Bars", "environment", "dungeon"],
  ]),
  ...kenneyPack("modular-buildings", "modular-buildings", "model", [
    ["kenney_mbld_wall", "Building Wall", "environment", "building", "modular"],
    ["kenney_mbld_window", "Building Window", "environment", "building"],
    ["kenney_mbld_door", "Building Door", "prop", "building", "door"],
    ["kenney_mbld_roof", "Building Roof", "environment", "building"],
    ["kenney_mbld_stairs", "Building Stairs", "environment", "building"],
    ["kenney_mbld_balcony", "Balcony", "environment", "building"],
  ]),
  ...kenneyPack("racing-kit", "racing-kit", "model", [
    ["kenney_race_car", "Race Car", "prop", "vehicle", "racing"],
    ["kenney_race_track", "Track Straight", "environment", "racing"],
    ["kenney_race_curve", "Track Curve", "environment", "racing"],
    ["kenney_race_finish", "Finish Gate", "prop", "racing"],
    ["kenney_race_cone", "Race Cone", "prop", "racing"],
    ["kenney_race_tires", "Tire Stack", "prop", "racing"],
    ["kenney_race_grandstand", "Grandstand", "environment", "racing"],
    ["kenney_race_pit", "Pit Stop", "environment", "racing"],
  ]),
  ...kenneyPack("blaster-kit", "blaster-kit", "model", [
    ["kenney_blast_pistol", "Blaster Pistol", "prop", "weapon", "scifi"],
    ["kenney_blast_rifle", "Blaster Rifle", "prop", "weapon", "scifi"],
    ["kenney_blast_crate", "Ammo Crate", "prop", "weapon", "crate"],
    ["kenney_blast_grenade", "Throwable", "prop", "weapon"],
    ["kenney_blast_silencer", "Silencer", "prop", "weapon"],
    ["kenney_blast_scope", "Scope", "prop", "weapon"],
    ["kenney_blast_holster", "Holster", "prop", "weapon"],
  ]),
  ...kenneyPack("train-kit", "train-kit", "model", [
    ["kenney_train_loco", "Locomotive", "prop", "vehicle", "train"],
    ["kenney_train_cargo", "Cargo Car", "prop", "vehicle", "train"],
    ["kenney_train_passenger", "Passenger Car", "prop", "vehicle", "train"],
    ["kenney_train_track", "Train Track", "environment", "train"],
    ["kenney_train_switch", "Track Switch", "environment", "train"],
    ["kenney_train_station", "Train Station", "environment", "train", "building"],
    ["kenney_train_signal", "Rail Signal", "prop", "train"],
  ]),
  ...kenneyPack("watercraft-kit", "watercraft-kit", "model", [
    ["kenney_boat_sail", "Sailboat", "prop", "vehicle", "boat"],
    ["kenney_boat_motor", "Motorboat", "prop", "vehicle", "boat"],
    ["kenney_boat_canoe", "Canoe", "prop", "vehicle", "boat"],
    ["kenney_boat_buoy", "Buoy", "prop", "boat"],
    ["kenney_boat_dock", "Boat Dock", "environment", "boat"],
    ["kenney_boat_sail_piece", "Sail", "prop", "boat"],
    ["kenney_boat_flag", "Boat Flag", "prop", "boat", "flag"],
  ]),
  ...kenneyPack("minigolf-kit", "minigolf-kit", "model", [
    ["kenney_golf_ball", "Golf Ball", "prop", "minigolf"],
    ["kenney_golf_club", "Golf Club", "prop", "minigolf"],
    ["kenney_golf_hole", "Golf Hole", "environment", "minigolf"],
    ["kenney_golf_windmill", "Golf Windmill", "environment", "minigolf"],
    ["kenney_golf_loop", "Loop-de-Loop", "environment", "minigolf", "obby"],
    ["kenney_golf_ramp", "Golf Ramp", "environment", "minigolf"],
    ["kenney_golf_wall", "Course Wall", "environment", "minigolf"],
  ]),
  ...kenneyPack("tower-defense-kit", "tower-defense-kit", "model", [
    ["kenney_td_tower", "Defense Tower", "prop", "towerdefense"],
    ["kenney_td_cannon", "TD Cannon", "prop", "towerdefense", "weapon"],
    ["kenney_td_path", "Enemy Path", "environment", "towerdefense"],
    ["kenney_td_base", "Player Base", "environment", "towerdefense"],
    ["kenney_td_spawn", "Spawn Portal", "prop", "towerdefense"],
    ["kenney_td_wall", "TD Wall", "environment", "towerdefense"],
    ["kenney_td_crystal", "Mana Crystal", "prop", "towerdefense"],
  ]),
  ...kenneyPack("survival-kit", "survival-kit", "model", [
    ["kenney_surv_axe", "Survival Axe", "prop", "survival", "weapon"],
    ["kenney_surv_camp", "Camp Tent", "environment", "survival"],
    ["kenney_surv_fire", "Camp Fire", "prop", "survival"],
    ["kenney_surv_crate", "Supply Crate", "prop", "survival", "crate"],
    ["kenney_surv_backpack", "Backpack", "prop", "survival"],
    ["kenney_surv_radio", "Radio", "prop", "survival"],
    ["kenney_surv_fence", "Barricade", "environment", "survival"],
  ]),
  ...kenneyPack("prototype-kit", "prototype-kit", "model", [
    ["kenney_proto_cube", "Prototype Cube", "environment", "prototype", "obby"],
    ["kenney_proto_ramp", "Prototype Ramp", "environment", "prototype", "obby"],
    ["kenney_proto_sphere", "Prototype Sphere", "prop", "prototype"],
    ["kenney_proto_cylinder", "Prototype Cylinder", "prop", "prototype"],
    ["kenney_proto_wedge", "Prototype Wedge", "environment", "prototype"],
    ["kenney_proto_grid", "Prototype Grid", "environment", "prototype"],
  ]),
  ...kenneyPack("brick-kit", "brick-kit", "model", [
    ["kenney_brick3_1x1", "Brick 1x1", "prop", "brick", "lego"],
    ["kenney_brick3_2x4", "Brick 2x4", "prop", "brick"],
    ["kenney_brick3_plate", "Brick Plate", "environment", "brick"],
    ["kenney_brick3_slope", "Brick Slope", "prop", "brick"],
    ["kenney_brick3_round", "Brick Round", "prop", "brick"],
    ["kenney_brick3_minifig", "Brick Figure", "character", "brick"],
  ]),
  ...kenneyPack("building-kit", "building-kit", "model", [
    ["kenney_bkit_wall", "Kit Wall", "environment", "building"],
    ["kenney_bkit_floor", "Kit Floor", "environment", "building"],
    ["kenney_bkit_column", "Kit Column", "environment", "building"],
    ["kenney_bkit_beam", "Kit Beam", "environment", "building"],
    ["kenney_bkit_stairs", "Kit Stairs", "environment", "building"],
  ]),
  ...kenneyPack("retro-fantasy-kit", "retro-fantasy-kit", "model", [
    ["kenney_rfant_hero", "Retro Hero", "character", "fantasy", "rpg"],
    ["kenney_rfant_mage", "Retro Mage", "character", "fantasy"],
    ["kenney_rfant_dragon", "Retro Dragon", "character", "fantasy", "enemy"],
    ["kenney_rfant_chest", "Retro Chest", "prop", "fantasy", "loot"],
    ["kenney_rfant_potion", "Retro Potion", "prop", "fantasy"],
    ["kenney_rfant_sword", "Retro Sword", "prop", "fantasy", "weapon"],
  ]),
  ...kenneyPack("retro-urban-kit", "retro-urban-kit", "model", [
    ["kenney_rurb_building", "Retro Building", "environment", "city", "retro"],
    ["kenney_rurb_car", "Retro Car", "prop", "vehicle", "retro"],
    ["kenney_rurb_lamp", "Retro Lamp", "prop", "city", "light"],
    ["kenney_rurb_dumpster", "Retro Dumpster", "prop", "city"],
    ["kenney_rurb_sign", "Retro Sign", "prop", "city", "sign"],
  ]),
  ...kenneyPack("toy-car-kit", "toy-car-kit", "model", [
    ["kenney_toy_racer", "Toy Racer", "prop", "vehicle", "toy"],
    ["kenney_toy_truck", "Toy Truck", "prop", "vehicle", "toy"],
    ["kenney_toy_bus", "Toy Bus", "prop", "vehicle", "toy"],
    ["kenney_toy_ramp", "Toy Ramp", "environment", "toy"],
    ["kenney_toy_loop", "Toy Loop", "environment", "toy", "obby"],
  ]),
  ...kenneyPack("cube-pets", "cube-pets", "model", [
    ["kenney_pet_cat", "Cube Cat", "character", "pet", "animal"],
    ["kenney_pet_dog", "Cube Dog", "character", "pet", "animal"],
    ["kenney_pet_bunny", "Cube Bunny", "character", "pet", "animal"],
    ["kenney_pet_dragon", "Cube Dragon", "character", "pet"],
    ["kenney_pet_slime", "Cube Slime", "character", "pet"],
    ["kenney_pet_bird", "Cube Bird", "character", "pet", "animal"],
  ]),
  ...kenneyPack("toon-characters", "toon-characters", "model", [
    ["kenney_toon_boy", "Toon Boy", "character", "npc", "toon"],
    ["kenney_toon_girl", "Toon Girl", "character", "npc", "toon"],
    ["kenney_toon_worker", "Toon Worker", "character", "npc"],
    ["kenney_toon_cop", "Toon Cop", "character", "npc"],
    ["kenney_toon_robot", "Toon Robot", "character", "npc"],
  ]),
  ...kenneyPack("blocky-characters", "blocky-characters", "model", [
    ["kenney_blocky_hero", "Blocky Hero", "character", "npc"],
    ["kenney_blocky_enemy", "Blocky Enemy", "character", "enemy"],
    ["kenney_blocky_npc", "Blocky Villager", "character", "npc"],
    ["kenney_blocky_knight", "Blocky Knight", "character", "npc"],
  ]),
  ...kenneyPack(
    "animated-characters-protagonists",
    "animated-characters-protagonists",
    "model",
    [
      ["kenney_hero_adventurer", "Adventurer", "character", "npc", "hero"],
      ["kenney_hero_rogue", "Rogue", "character", "npc", "hero"],
      ["kenney_hero_ranger", "Ranger", "character", "npc", "hero"],
      ["kenney_hero_cleric", "Cleric", "character", "npc", "hero"],
    ],
  ),
  ...kenneyPack(
    "animated-characters-survivors",
    "animated-characters-survivors",
    "model",
    [
      ["kenney_survchar_survivor", "Survivor", "character", "npc"],
      ["kenney_survchar_zombie", "Zombie", "character", "enemy", "undead"],
      ["kenney_survchar_soldier", "Soldier", "character", "npc"],
      ["kenney_survchar_medic", "Medic", "character", "npc"],
    ],
  ),
  ...kenneyPack("animated-characters-retro", "animated-characters-retro", "model", [
    ["kenney_retrochar_hero", "Retro Character", "character", "npc"],
    ["kenney_retrochar_enemy", "Retro Enemy", "character", "enemy"],
    ["kenney_retrochar_npc", "Retro Townsfolk", "character", "npc"],
  ]),
  ...kenneyPack("modular-characters", "modular-characters", "model", [
    ["kenney_modchar_head", "Modular Head", "character", "modular"],
    ["kenney_modchar_body", "Modular Body", "character", "modular"],
    ["kenney_modchar_hat", "Modular Hat", "prop", "modular"],
    ["kenney_modchar_weapon", "Modular Weapon", "prop", "modular", "weapon"],
  ]),
  ...kenneyPack("mini-forest", "mini-forest", "model", [
    ["kenney_mfor_pine", "Mini Pine", "environment", "tree", "mini"],
    ["kenney_mfor_oak", "Mini Oak", "environment", "tree", "mini"],
    ["kenney_mfor_rock", "Mini Rock", "environment", "rock", "mini"],
    ["kenney_mfor_mushroom", "Mini Mushroom", "environment", "mini"],
    ["kenney_mfor_log", "Mini Log", "environment", "mini"],
    ["kenney_mfor_flower", "Mini Flower", "environment", "mini"],
  ]),
  ...kenneyPack("mini-arcade", "mini-arcade", "model", [
    ["kenney_marc_cabinet", "Arcade Cabinet", "prop", "arcade"],
    ["kenney_marc_token", "Arcade Token", "prop", "arcade", "currency"],
    ["kenney_marc_joystick", "Joystick", "prop", "arcade"],
    ["kenney_marc_prize", "Prize Plush", "prop", "arcade"],
  ]),
  ...kenneyPack("mini-arena", "mini-arena", "model", [
    ["kenney_marena_ring", "Arena Ring", "environment", "arena"],
    ["kenney_marena_pillar", "Arena Pillar", "environment", "arena"],
    ["kenney_marena_gate", "Arena Gate", "environment", "arena"],
    ["kenney_marena_banner", "Arena Banner", "prop", "arena", "flag"],
  ]),
  ...kenneyPack("mini-characters", "mini-characters", "model", [
    ["kenney_mchar_hero", "Mini Hero", "character", "mini"],
    ["kenney_mchar_npc", "Mini NPC", "character", "mini"],
    ["kenney_mchar_enemy", "Mini Enemy", "character", "mini", "enemy"],
  ]),
  ...kenneyPack("mini-market", "mini-market", "model", [
    ["kenney_mmarket_stall", "Market Stall", "environment", "shop", "mini"],
    ["kenney_mmarket_crate", "Produce Crate", "prop", "shop", "mini"],
    ["kenney_mmarket_sign", "Shop Sign", "prop", "shop", "mini"],
    ["kenney_mmarket_cart", "Market Cart", "prop", "shop", "mini"],
  ]),
  ...kenneyPack("mini-skate", "mini-skate", "model", [
    ["kenney_mskate_ramp", "Skate Ramp", "environment", "skate", "obby"],
    ["kenney_mskate_rail", "Grind Rail", "environment", "skate", "obby"],
    ["kenney_mskate_board", "Skateboard", "prop", "skate"],
    ["kenney_mskate_halfpipe", "Halfpipe", "environment", "skate"],
  ]),
  ...kenneyPack("marble-kit", "marble-kit", "model", [
    ["kenney_marble_ball", "Marble", "prop", "marble", "obby"],
    ["kenney_marble_track", "Marble Track", "environment", "marble", "obby"],
    ["kenney_marble_funnel", "Marble Funnel", "environment", "marble"],
    ["kenney_marble_spinner", "Marble Spinner", "prop", "marble"],
  ]),
  ...kenneyPack("coaster-kit", "coaster-kit", "model", [
    ["kenney_coaster_car", "Coaster Car", "prop", "coaster", "vehicle"],
    ["kenney_coaster_track", "Coaster Track", "environment", "coaster", "obby"],
    ["kenney_coaster_loop", "Coaster Loop", "environment", "coaster"],
    ["kenney_coaster_support", "Track Support", "environment", "coaster"],
  ]),
  ...kenneyPack("sci-fi-rts", "sci-fi-rts", "model", [
    ["kenney_scirts_hq", "Sci-Fi HQ", "environment", "rts", "scifi"],
    ["kenney_scirts_turret", "RTS Turret", "prop", "rts", "weapon"],
    ["kenney_scirts_unit", "RTS Unit", "character", "rts"],
    ["kenney_scirts_res", "Resource Node", "prop", "rts"],
    ["kenney_scirts_wall", "Base Wall", "environment", "rts"],
  ]),
  ...kenneyPack("medieval-rts", "medieval-rts", "model", [
    ["kenney_medrts_keep", "RTS Keep", "environment", "rts", "medieval"],
    ["kenney_medrts_barracks", "Barracks", "environment", "rts"],
    ["kenney_medrts_farm", "Farm Plot", "environment", "rts"],
    ["kenney_medrts_knight", "RTS Knight", "character", "rts"],
    ["kenney_medrts_siege", "Siege Engine", "prop", "rts"],
  ]),
  ...kenneyPack("3d-road-tiles", "3d-road-tiles", "model", [
    ["kenney_road3d_straight", "3D Road Straight", "environment", "city", "road"],
    ["kenney_road3d_curve", "3D Road Curve", "environment", "city", "road"],
    ["kenney_road3d_t", "3D Road T-Junction", "environment", "city", "road"],
    ["kenney_road3d_cross", "3D Road Cross", "environment", "city", "road"],
  ]),
  ...kenneyPack("holiday-extras", "holiday-extras", "model", [
    ["kenney_holix_candy", "Candy Cane", "prop", "holiday"],
    ["kenney_holix_lights", "String Lights", "prop", "holiday"],
    ["kenney_holix_star", "Tree Star", "prop", "holiday"],
    ["kenney_holix_stocking", "Stocking", "prop", "holiday"],
  ]),
  ...kenneyPack("pixel-platformer", "pixel-platformer", "image", [
    ["kenney_pxplat_hero", "Pixel Hero", "ui", "pixel", "obby"],
    ["kenney_pxplat_tiles", "Pixel Tiles", "ui", "pixel"],
    ["kenney_pxplat_enemy", "Pixel Enemy", "ui", "pixel"],
    ["kenney_pxplat_coin", "Pixel Coin", "ui", "pixel", "currency"],
    ["kenney_pxplat_flag", "Pixel Flag", "ui", "pixel", "checkpoint"],
  ]),
  ...kenneyPack("new-platformer-pack", "new-platformer-pack", "image", [
    ["kenney_newplat_tiles", "New Plat Tiles", "ui", "obby"],
    ["kenney_newplat_hero", "New Plat Hero", "ui", "obby"],
    ["kenney_newplat_hazard", "New Plat Hazard", "ui", "obby"],
    ["kenney_newplat_bg", "New Plat Background", "ui", "obby"],
  ]),
  ...kenneyPack("game-icons", "game-icons", "image", [
    ["kenney_gicon_attack", "Icon Attack", "ui", "icon", "combat"],
    ["kenney_gicon_defend", "Icon Defend", "ui", "icon", "combat"],
    ["kenney_gicon_magic", "Icon Magic", "ui", "icon"],
    ["kenney_gicon_loot", "Icon Loot", "ui", "icon"],
    ["kenney_gicon_craft", "Icon Craft", "ui", "icon"],
    ["kenney_gicon_mount", "Icon Mount", "ui", "icon"],
    ["kenney_gicon_pet", "Icon Pet", "ui", "icon"],
    ["kenney_gicon_guild", "Icon Guild", "ui", "icon"],
  ]),
  ...kenneyPack("game-icons-expansion", "game-icons-expansion", "image", [
    ["kenney_giconx_fish", "Icon Fish", "ui", "icon"],
    ["kenney_giconx_mine", "Icon Mine", "ui", "icon"],
    ["kenney_giconx_farm", "Icon Farm", "ui", "icon"],
    ["kenney_giconx_pvp", "Icon PvP", "ui", "icon", "combat"],
    ["kenney_giconx_event", "Icon Event", "ui", "icon"],
  ]),
  ...kenneyPack("emotes-pack", "emotes-pack", "image", [
    ["kenney_emote_happy", "Emote Happy", "ui", "emote"],
    ["kenney_emote_sad", "Emote Sad", "ui", "emote"],
    ["kenney_emote_angry", "Emote Angry", "ui", "emote"],
    ["kenney_emote_wave", "Emote Wave", "ui", "emote"],
    ["kenney_emote_gg", "Emote GG", "ui", "emote"],
    ["kenney_emote_heart", "Emote Heart", "ui", "emote"],
  ]),
  ...kenneyPack("medals", "medals", "image", [
    ["kenney_medal_gold", "Gold Medal", "ui", "medal"],
    ["kenney_medal_silver", "Silver Medal", "ui", "medal"],
    ["kenney_medal_bronze", "Bronze Medal", "ui", "medal"],
    ["kenney_medal_star", "Star Medal", "ui", "medal"],
  ]),
  ...kenneyPack("cursor-pack", "cursor-pack", "image", [
    ["kenney_cursor_default", "Cursor Default", "ui", "cursor"],
    ["kenney_cursor_pointer", "Cursor Pointer", "ui", "cursor"],
    ["kenney_cursor_attack", "Cursor Attack", "ui", "cursor"],
    ["kenney_cursor_busy", "Cursor Busy", "ui", "cursor"],
  ]),
  ...kenneyPack("crosshair-pack", "crosshair-pack", "image", [
    ["kenney_xhair_dot", "Crosshair Dot", "ui", "crosshair"],
    ["kenney_xhair_circle", "Crosshair Circle", "ui", "crosshair"],
    ["kenney_xhair_sniper", "Crosshair Sniper", "ui", "crosshair"],
  ]),
  ...kenneyPack("flag-pack", "flag-pack", "image", [
    ["kenney_flag2_red", "Flag Red", "ui", "flag"],
    ["kenney_flag2_blue", "Flag Blue", "ui", "flag"],
    ["kenney_flag2_green", "Flag Green", "ui", "flag"],
    ["kenney_flag2_check", "Flag Checkered", "ui", "flag", "racing"],
  ]),
  ...kenneyPack("pixel-ui-pack", "pixel-ui-pack", "image", [
    ["kenney_pui_button", "Pixel UI Button", "ui", "pixel"],
    ["kenney_pui_panel", "Pixel UI Panel", "ui", "pixel"],
    ["kenney_pui_bar", "Pixel UI Bar", "ui", "pixel"],
    ["kenney_pui_slot", "Pixel UI Slot", "ui", "pixel"],
  ]),
  ...kenneyPack("ui-pack-adventure", "ui-pack-adventure", "image", [
    ["kenney_uiadv_frame", "Adventure Frame", "ui", "rpg"],
    ["kenney_uiadv_btn", "Adventure Button", "ui", "rpg"],
    ["kenney_uiadv_portrait", "Portrait Frame", "ui", "rpg"],
  ]),
  ...kenneyPack("ui-pack-rpg-expansion", "ui-pack-rpg-expansion", "image", [
    ["kenney_uirpg_skill", "Skill Slot", "ui", "rpg"],
    ["kenney_uirpg_xp", "XP Frame", "ui", "rpg"],
    ["kenney_uirpg_quest", "Quest Panel", "ui", "rpg"],
  ]),
  ...kenneyPack("ui-pack-sci-fi", "ui-pack-sci-fi", "image", [
    ["kenney_uisci_hud", "Sci-Fi HUD", "ui", "scifi"],
    ["kenney_uisci_btn", "Sci-Fi Button", "ui", "scifi"],
    ["kenney_uisci_radar", "Radar Widget", "ui", "scifi"],
  ]),
  ...kenneyPack("board-game-icons", "board-game-icons", "image", [
    ["kenney_bgicon_meeple", "Meeple", "ui", "boardgame"],
    ["kenney_bgicon_dice", "Dice Icon", "ui", "boardgame"],
    ["kenney_bgicon_token", "Token Icon", "ui", "boardgame"],
  ]),
  ...kenneyPack("letter-tiles", "letter-tiles", "image", [
    ["kenney_letter_a", "Letter A", "ui", "letter"],
    ["kenney_letter_b", "Letter B", "ui", "letter"],
    ["kenney_letter_q", "Letter Q", "ui", "letter"],
    ["kenney_letter_blank", "Blank Tile", "ui", "letter"],
  ]),
  ...kenneyPack("playing-cards-pack", "playing-cards-pack", "image", [
    ["kenney_card_ace", "Ace of Spades", "ui", "cards"],
    ["kenney_card_joker", "Joker", "ui", "cards"],
    ["kenney_card_back", "Card Back", "ui", "cards"],
  ]),
  ...kenneyPack("smoke-particles", "smoke-particles", "image", [
    ["kenney_smoke_puff", "Smoke Puff", "ui", "vfx"],
    ["kenney_smoke_cloud", "Smoke Cloud", "ui", "vfx"],
    ["kenney_smoke_trail", "Smoke Trail", "ui", "vfx"],
  ]),
  ...kenneyPack("particle-pack", "particle-pack", "image", [
    ["kenney_part_spark", "Spark", "ui", "vfx"],
    ["kenney_part_star", "Star Burst", "ui", "vfx"],
    ["kenney_part_circle", "Circle Burst", "ui", "vfx"],
    ["kenney_part_slash", "Slash FX", "ui", "vfx", "combat"],
  ]),
  ...kenneyPack("light-masks", "light-masks", "image", [
    ["kenney_lmask_circle", "Light Mask Circle", "ui", "vfx", "light"],
    ["kenney_lmask_cone", "Light Mask Cone", "ui", "vfx", "light"],
    ["kenney_lmask_soft", "Light Mask Soft", "ui", "vfx", "light"],
  ]),
  ...kenneyPack("mobile-controls", "mobile-controls", "image", [
    ["kenney_mctrl_stick", "Virtual Stick", "ui", "mobile"],
    ["kenney_mctrl_jump", "Jump Button", "ui", "mobile"],
    ["kenney_mctrl_fire", "Fire Button", "ui", "mobile"],
  ]),
  ...kenneyPack("input-prompts-pixel", "input-prompts-pixel", "image", [
    ["kenney_pxprompt_a", "Pixel Prompt A", "ui", "prompt", "pixel"],
    ["kenney_pxprompt_b", "Pixel Prompt B", "ui", "prompt", "pixel"],
    ["kenney_pxprompt_wasd", "Pixel WASD", "ui", "prompt", "pixel"],
  ]),
  ...kenneyPack("tiny-town", "tiny-town", "image", [
    ["kenney_ttown_house", "Tiny House", "ui", "tiny", "pixel"],
    ["kenney_ttown_tree", "Tiny Tree", "ui", "tiny"],
    ["kenney_ttown_road", "Tiny Road", "ui", "tiny"],
    ["kenney_ttown_npc", "Tiny Villager", "ui", "tiny"],
  ]),
  ...kenneyPack("tiny-dungeon", "tiny-dungeon", "image", [
    ["kenney_tdung_wall", "Tiny Dungeon Wall", "ui", "tiny", "dungeon"],
    ["kenney_tdung_chest", "Tiny Chest", "ui", "tiny"],
    ["kenney_tdung_hero", "Tiny Dungeon Hero", "ui", "tiny"],
    ["kenney_tdung_slime", "Tiny Slime", "ui", "tiny", "enemy"],
  ]),
  ...kenneyPack("tiny-battle", "tiny-battle", "image", [
    ["kenney_tbattle_soldier", "Tiny Soldier", "ui", "tiny"],
    ["kenney_tbattle_tank", "Tiny Tank", "ui", "tiny"],
    ["kenney_tbattle_flag", "Tiny Battle Flag", "ui", "tiny"],
  ]),
  ...kenneyPack("tiny-farm", "tiny-farm", "image", [
    ["kenney_tfarm_barn", "Tiny Barn", "ui", "tiny", "farm"],
    ["kenney_tfarm_crop", "Tiny Crop", "ui", "tiny", "farm"],
    ["kenney_tfarm_cow", "Tiny Cow", "ui", "tiny", "animal"],
  ]),
  ...kenneyPack("tiny-factory", "tiny-factory", "image", [
    ["kenney_tfact_belt", "Tiny Conveyor", "ui", "tiny", "factory"],
    ["kenney_tfact_machine", "Tiny Machine", "ui", "tiny", "factory"],
    ["kenney_tfact_crate", "Tiny Factory Crate", "ui", "tiny"],
  ]),
  ...kenneyPack("tiny-ski", "tiny-ski", "image", [
    ["kenney_tski_slope", "Tiny Slope", "ui", "tiny", "snow"],
    ["kenney_tski_skier", "Tiny Skier", "ui", "tiny"],
    ["kenney_tski_tree", "Tiny Snow Tree", "ui", "tiny"],
  ]),
  ...kenneyPack("scribble-platformer", "scribble-platformer", "image", [
    ["kenney_scrib_hero", "Scribble Hero", "ui", "scribble", "obby"],
    ["kenney_scrib_tile", "Scribble Tile", "ui", "scribble"],
    ["kenney_scrib_spike", "Scribble Spike", "ui", "scribble"],
  ]),
  ...kenneyPack("skyboxes", "skyboxes", "texture", [
    ["kenney_sky_day", "Skybox Day", "texture", "sky"],
    ["kenney_sky_sunset", "Skybox Sunset", "texture", "sky"],
    ["kenney_sky_night", "Skybox Night", "texture", "sky"],
    ["kenney_sky_space", "Skybox Space", "texture", "sky", "space"],
  ]),
  ...kenneyPack("prototype-textures", "prototype-textures", "texture", [
    ["kenney_ptex_grid", "Prototype Grid Tex", "texture", "prototype"],
    ["kenney_ptex_orange", "Prototype Orange", "texture", "prototype"],
    ["kenney_ptex_dark", "Prototype Dark", "texture", "prototype"],
  ]),
  ...kenneyPack("pattern-pack", "pattern-pack", "texture", [
    ["kenney_pat_dots", "Pattern Dots", "texture", "pattern"],
    ["kenney_pat_stripes", "Pattern Stripes", "texture", "pattern"],
    ["kenney_pat_check", "Pattern Check", "texture", "pattern"],
  ]),
  ...kenneyPack("road-textures", "road-textures", "texture", [
    ["kenney_rtex_asphalt", "Asphalt Tex", "texture", "road"],
    ["kenney_rtex_dirt", "Dirt Road Tex", "texture", "road"],
    ["kenney_rtex_line", "Road Line Tex", "texture", "road"],
  ]),
  ...kenneyPack("planets", "planets", "image", [
    ["kenney_planet_earth", "Planet Earth", "ui", "space"],
    ["kenney_planet_mars", "Planet Mars", "ui", "space"],
    ["kenney_planet_gas", "Gas Giant", "ui", "space"],
    ["kenney_planet_moon", "Moon", "ui", "space"],
  ]),
  ...kenneyPack("ranks-pack", "ranks-pack", "image", [
    ["kenney_rank_bronze", "Rank Bronze", "ui", "rank"],
    ["kenney_rank_silver", "Rank Silver", "ui", "rank"],
    ["kenney_rank_gold", "Rank Gold", "ui", "rank"],
    ["kenney_rank_legend", "Rank Legend", "ui", "rank"],
  ]),
  ...kenneyPack(
    "interface-sounds",
    "interface-sounds",
    "audio",
    [
      ["kenney_sfx_iface_open", "UI Open", "audio", "ui"],
      ["kenney_sfx_iface_close", "UI Close", "audio", "ui"],
      ["kenney_sfx_iface_select", "UI Select", "audio", "ui"],
      ["kenney_sfx_iface_deny", "UI Deny", "audio", "ui"],
      ["kenney_sfx_iface_notify", "UI Notify", "audio", "ui"],
    ],
    { uploadSupported: false },
  ),
  ...kenneyPack(
    "ui-audio",
    "ui-audio",
    "audio",
    [
      ["kenney_sfx_ui2_beep", "UI Beep", "audio", "ui"],
      ["kenney_sfx_ui2_switch", "UI Switch", "audio", "ui"],
      ["kenney_sfx_ui2_type", "UI Type", "audio", "ui"],
    ],
    { uploadSupported: false },
  ),
  ...kenneyPack(
    "sci-fi-sounds",
    "sci-fi-sounds",
    "audio",
    [
      ["kenney_sfx_scifi_blaster", "Blaster Shot", "audio", "scifi", "combat"],
      ["kenney_sfx_scifi_shield", "Shield Hit", "audio", "scifi"],
      ["kenney_sfx_scifi_teleport", "Teleport", "audio", "scifi"],
      ["kenney_sfx_scifi_alarm", "Alarm", "audio", "scifi"],
    ],
    { uploadSupported: false },
  ),
  ...kenneyPack(
    "digital-audio",
    "digital-audio",
    "audio",
    [
      ["kenney_sfx_digital_blip", "Digital Blip", "audio"],
      ["kenney_sfx_digital_power", "Power On", "audio"],
      ["kenney_sfx_digital_glitch", "Glitch", "audio"],
    ],
    { uploadSupported: false },
  ),
  ...kenneyPack(
    "music-jingles",
    "music-jingles",
    "audio",
    [
      ["kenney_jingle_win", "Win Jingle", "audio", "music"],
      ["kenney_jingle_lose", "Lose Jingle", "audio", "music"],
      ["kenney_jingle_bonus", "Bonus Jingle", "audio", "music"],
      ["kenney_jingle_start", "Start Jingle", "audio", "music"],
    ],
    { uploadSupported: false },
  ),
  ...kenneyPack(
    "casino-audio",
    "casino-audio",
    "audio",
    [
      ["kenney_casino_spin", "Slot Spin", "audio", "casino"],
      ["kenney_casino_win", "Jackpot", "audio", "casino"],
      ["kenney_casino_chip", "Chip", "audio", "casino"],
    ],
    { uploadSupported: false },
  ),
  ...kenneyPack(
    "voiceover-pack",
    "voiceover-pack",
    "audio",
    [
      ["kenney_vo_go", "Voice Go", "audio", "voice"],
      ["kenney_vo_yes", "Voice Yes", "audio", "voice"],
      ["kenney_vo_no", "Voice No", "audio", "voice"],
      ["kenney_vo_ready", "Voice Ready", "audio", "voice"],
    ],
    { uploadSupported: false },
  ),
];

export const QUATERNIUS_DEEP_ASSETS: CatalogAsset[] = quatPack([
  ["quat_lion", "Lion", "character", "animal"],
  ["quat_elephant", "Elephant", "character", "animal"],
  ["quat_dragon", "Dragon", "character", "enemy", "fantasy"],
  ["quat_dino_trex", "T-Rex", "character", "enemy", "dinosaur"],
  ["quat_dino_raptor", "Raptor", "character", "enemy", "dinosaur"],
  ["quat_spaceship_fighter", "Fighter Ship", "prop", "space", "vehicle"],
  ["quat_spaceship_cargo", "Cargo Ship", "prop", "space", "vehicle"],
  ["quat_cyber_street", "Cyber Street", "environment", "cyberpunk"],
  ["quat_cyber_neon", "Neon Sign", "prop", "cyberpunk"],
  ["quat_cyber_enemy", "Cyber Enemy", "character", "cyberpunk", "enemy"],
  ["quat_cyber_turret", "Cyber Turret", "prop", "cyberpunk", "weapon"],
  ["quat_scifi_corridor", "Sci-Fi Corridor", "environment", "scifi", "modular"],
  ["quat_scifi_door", "Sci-Fi Door", "prop", "scifi", "door"],
  ["quat_scifi_console", "Sci-Fi Console", "prop", "scifi"],
  ["quat_scifi_crate", "Sci-Fi Crate", "prop", "scifi", "crate"],
  ["quat_scifi_gun", "Sci-Fi Gun", "prop", "scifi", "weapon"],
  ["quat_ruin_arch", "Ruin Arch", "environment", "ruins"],
  ["quat_ruin_pillar", "Ruin Pillar", "environment", "ruins"],
  ["quat_ruin_rubble", "Rubble", "environment", "ruins"],
  ["quat_dungeon_wall", "Modular Dungeon Wall", "environment", "dungeon"],
  ["quat_dungeon_stairs", "Dungeon Stairs", "environment", "dungeon"],
  ["quat_dungeon_trap", "Dungeon Trap", "prop", "dungeon", "hazard"],
  ["quat_dungeon_potion", "Dungeon Potion", "prop", "dungeon"],
  ["quat_robot", "Robot", "character", "scifi"],
  ["quat_monster_cute", "Cute Monster", "character", "enemy"],
  ["quat_monster_golem", "Golem", "character", "enemy"],
  ["quat_knight", "Knight", "character", "npc", "fantasy"],
  ["quat_wizard", "Wizard", "character", "npc", "fantasy"],
  ["quat_archer", "Archer", "character", "npc", "fantasy"],
  ["quat_truck", "Truck", "prop", "vehicle"],
  ["quat_van", "Van", "prop", "vehicle"],
  ["quat_helicopter", "Helicopter", "prop", "vehicle"],
  ["quat_tank", "Tank", "prop", "vehicle", "weapon"],
  ["quat_train", "Train", "prop", "vehicle"],
  ["quat_tree_palm", "Palm Tree", "environment", "tree"],
  ["quat_tree_dead", "Dead Tree", "environment", "tree"],
  ["quat_bush", "Bush", "environment", "plant"],
  ["quat_rock_crystal", "Crystal Rock", "environment", "rock"],
  ["quat_platform_grass", "Grass Platform", "environment", "obby"],
  ["quat_platform_cloud", "Cloud Platform", "environment", "obby"],
  ["quat_checkpoint", "Checkpoint Flag", "prop", "obby", "checkpoint"],
  ["quat_hazard_spike", "Spike Hazard", "prop", "obby", "hazard"],
  ["quat_food_taco", "Taco", "prop", "food"],
  ["quat_food_donut", "Donut", "prop", "food"],
  ["quat_food_soda", "Soda", "prop", "food"],
  ["quat_weapon_gun", "Gun", "prop", "weapon"],
  ["quat_weapon_staff", "Staff", "prop", "weapon", "magic"],
  ["quat_weapon_bow", "Bow", "prop", "weapon"],
  ["quat_outfit_helm", "Fantasy Helm", "prop", "armor"],
  ["quat_outfit_cloak", "Fantasy Cloak", "prop", "armor"],
]);

const PH_TEXTURES: [string, string, string[]][] = [
  ["wood_table_worn", "Wood Table Worn", ["wood", "indoor"]],
  ["wood_cabinet_worn_long", "Wood Cabinet Worn", ["wood", "indoor"]],
  ["rocky_terrain_02", "Rocky Terrain 02", ["rock", "terrain"]],
  ["leather_red_02", "Red Leather 02", ["fabric", "leather"]],
  ["book_pattern", "Book Pattern", ["fabric"]],
  ["bark_brown_02", "Brown Bark 02", ["wood", "bark"]],
  ["rust_coarse_01", "Coarse Rust", ["metal"]],
  ["aerial_rocks_04", "Aerial Rocks 04", ["rock", "terrain"]],
  ["kitchen_wood", "Kitchen Wood", ["wood", "indoor"]],
  ["leather_white", "White Leather", ["fabric", "leather"]],
  ["denmin_fabric_02", "Denim Fabric", ["fabric"]],
  ["floor_tiles_06", "Floor Tiles 06", ["floor", "indoor"]],
  ["fabric_pattern_05", "Fabric Pattern 05", ["fabric"]],
  ["forest_ground_04", "Forest Ground 04", ["dirt", "outdoor"]],
  ["aerial_beach_01", "Aerial Beach", ["sand", "terrain"]],
  ["brown_planks_03", "Brown Planks 03", ["wood"]],
  ["forest_leaves_02", "Forest Leaves 02", ["dirt", "outdoor"]],
  ["granite_tile", "Granite Tile", ["floor"]],
  ["synthetic_wood", "Synthetic Wood", ["wood"]],
  ["wood_planks_dirt", "Wood Planks Dirt", ["wood", "outdoor"]],
  ["planks_brown_10", "Planks Brown 10", ["wood"]],
  ["wood_floor_deck", "Wood Floor Deck", ["wood", "outdoor"]],
  ["rocks_ground_02", "Rocks Ground 02", ["rock", "terrain"]],
  ["aerial_asphalt_01", "Aerial Asphalt", ["road", "city"]],
  ["red_brick_03", "Red Brick 03", ["brick", "wall"]],
  ["medieval_blocks_03", "Medieval Blocks", ["brick", "castle"]],
  ["rock_boulder_dry", "Dry Boulder", ["rock"]],
  ["laminate_floor_03", "Laminate Floor 03", ["floor", "wood"]],
  ["fine_grained_wood", "Fine Grained Wood", ["wood"]],
  ["weathered_planks", "Weathered Planks", ["wood", "outdoor"]],
  ["brick_4", "Brick 4", ["brick", "wall"]],
  ["concrete_layers_02", "Concrete Layers", ["concrete"]],
  ["wood_planks", "Wood Planks", ["wood"]],
  ["cracked_concrete_wall", "Cracked Concrete", ["concrete", "wall"]],
  ["castle_brick_02_red", "Castle Brick Red", ["brick", "castle"]],
  ["stone_tiles_02", "Stone Tiles 02", ["rock", "floor"]],
  ["rock_01", "Rock 01", ["rock"]],
  ["rustic_stone_wall_02", "Rustic Stone Wall", ["rock", "wall"]],
  ["leather_red_03", "Red Leather 03", ["fabric", "leather"]],
  ["rosewood_veneer1", "Rosewood Veneer", ["wood"]],
  ["bark_brown_01", "Brown Bark 01", ["wood", "bark"]],
  ["brown_mud_dry", "Dry Brown Mud", ["dirt", "terrain"]],
  ["large_floor_tiles_02", "Large Floor Tiles", ["floor"]],
  ["gray_rocks", "Gray Rocks", ["rock", "terrain"]],
  ["grey_plaster", "Grey Plaster", ["wall"]],
  ["aerial_rocks_01", "Aerial Rocks 01", ["rock", "terrain"]],
  ["old_planks_02", "Old Planks 02", ["wood"]],
  ["ganges_river_pebbles", "River Pebbles", ["rock", "terrain"]],
  ["floor_tiles_02", "Floor Tiles 02", ["floor"]],
  ["wood_planks_grey", "Grey Wood Planks", ["wood"]],
  ["plaster_grey_04", "Grey Plaster 04", ["wall"]],
  ["bark_willow", "Willow Bark", ["wood", "bark"]],
];

const PH_HDRIS: [string, string, string[]][] = [
  ["kloofendal_48d_partly_cloudy_puresky", "Kloofendal Pure Sky", ["sky", "day"]],
  ["brown_photostudio_02", "Brown Photostudio", ["studio"]],
  ["lilienstein", "Lilienstein", ["sky", "sunset"]],
  ["studio_small_09", "Studio Small 09", ["studio"]],
  ["dikhololo_night", "Dikhololo Night", ["night", "sky"]],
  ["satara_night", "Satara Night", ["night", "sky"]],
  ["the_sky_is_on_fire", "Sky On Fire", ["sunset", "sky"]],
  ["studio_small_08", "Studio Small 08", ["studio"]],
  ["kloppenheim_02", "Kloppenheim 02", ["night", "sky"]],
  ["spruit_sunrise", "Spruit Sunrise", ["sunrise", "sky"]],
  ["canary_wharf", "Canary Wharf", ["city", "sky"]],
  ["kloppenheim_06_puresky", "Kloppenheim 06 Pure Sky", ["sky"]],
  ["wide_street_01", "Wide Street", ["city"]],
  ["meadow_2", "Meadow 2", ["outdoor", "sky"]],
  ["shanghai_bund", "Shanghai Bund", ["city", "night"]],
  ["kiara_1_dawn", "Kiara Dawn", ["sunrise", "sky"]],
  ["belfast_sunset_puresky", "Belfast Sunset", ["sunset", "sky"]],
  ["autumn_field_puresky", "Autumn Field", ["outdoor", "sky"]],
  ["noon_grass", "Noon Grass", ["day", "sky"]],
  ["photo_studio_01", "Photo Studio 01", ["studio"]],
];

const PH_MODELS: [string, string, "prop" | "environment" | "character", string[]][] = [
  ["grass_medium_01", "Grass Medium 01", "environment", ["grass", "nature"]],
  ["tree_small_02", "Tree Small 02", "environment", ["tree", "nature"]],
  ["jacaranda_tree", "Jacaranda Tree", "environment", ["tree", "nature"]],
  ["Camera_01", "Camera 01", "prop", ["electronics"]],
  ["potted_plant_02", "Potted Plant 02", "prop", ["plant", "furniture"]],
  ["grass_bermuda_01", "Bermuda Grass", "environment", ["grass"]],
  ["marble_bust_01", "Marble Bust", "prop", ["decor"]],
  ["rock_moss_set_02", "Mossy Rocks", "environment", ["rock", "nature"]],
  ["Television_01", "Television 01", "prop", ["furniture"]],
  ["island_tree_02", "Island Tree 02", "environment", ["tree"]],
  ["potted_plant_04", "Potted Plant 04", "prop", ["plant"]],
  ["sofa_02", "Sofa 02", "prop", ["furniture"]],
  ["fern_02", "Fern 02", "environment", ["plant"]],
  ["celandine_01", "Celandine", "environment", ["flower"]],
  ["fir_tree_01", "Fir Tree 01", "environment", ["tree"]],
  ["decorative_book_set_01", "Book Set", "prop", ["furniture"]],
  ["Lantern_01", "Lantern 01", "prop", ["light"]],
  ["wooden_table_02", "Wooden Table 02", "prop", ["furniture"]],
  ["dandelion_01", "Dandelion", "environment", ["flower"]],
  ["wine_bottles_01", "Wine Bottles", "prop", ["food"]],
  ["Barrel_01", "Barrel 01", "prop", ["crate"]],
  ["food_apple_01", "Apple 01", "prop", ["food"]],
  ["ship_pinnace", "Ship Pinnace", "prop", ["boat", "vehicle"]],
  ["chess_set", "Chess Set", "prop", ["decor"]],
  ["tea_set_01", "Tea Set", "prop", ["food"]],
  ["rubber_duck_toy", "Rubber Duck", "prop", ["toy"]],
  ["street_rat", "Street Rat", "character", ["animal"]],
];

export const POLY_HAVEN_DEEP_ASSETS: CatalogAsset[] = [
  ...PH_TEXTURES.map(([slug, name, tags]) => polyHavenTexture(slug, name, tags)),
  ...PH_HDRIS.map(([slug, name, tags]) => polyHavenHdri(slug, name, tags)),
  ...PH_MODELS.map(([slug, name, category, tags]) =>
    polyHavenModel(slug, name, category, tags),
  ),
];
