/**
 * Extra CC0 catalog slots from official free sources Blockforge may index:
 * ambientCG (PBR + HDRI) and remaining Kenney audio kits.
 *
 * Not indexed (see SOURCES.md): Sketchfab scrape, Textures.com, Freesound API,
 * OpenGameArt bulk, itch.io, Roblox Creator Store / Toolbox.
 */
import type { CatalogAsset } from "./types.js";
import { kenneyPack } from "./seed-packs.js";

function acgTexture(
  assetId: string,
  name: string,
  tags: string[],
): CatalogAsset {
  const slug = assetId.toLowerCase();
  return {
    id: `acg_${slug}`,
    name,
    category: "texture",
    kind: "texture",
    tags: [...tags, "pbr", "ambientcg"],
    license: "CC0",
    attribution: "ambientCG (https://ambientcg.com) — CC0 1.0",
    source: `https://ambientcg.com/a/${assetId}`,
    packId: "ambientcg-cc0",
    uploadSupported: true,
  };
}

function acgHdri(assetId: string, name: string, tags: string[]): CatalogAsset {
  const slug = assetId.toLowerCase();
  return {
    id: `acg_hdri_${slug}`,
    name: `${name} (preview)`,
    category: "texture",
    kind: "hdri",
    tags: [...tags, "hdri", "ambientcg"],
    license: "CC0",
    attribution: "ambientCG (https://ambientcg.com) — CC0 1.0",
    source: `https://ambientcg.com/a/${assetId}`,
    packId: "ambientcg-cc0",
    uploadSupported: false,
  };
}

/** Top-download ambientCG materials (official API, sort=Downloads). */
const ACG_MATERIALS: [id: string, name: string, ...tags: string[]][] = [
  ["Road007", "Road 007", "asphalt", "road", "city"],
  ["Marble012", "Marble 012", "marble", "floor", "indoor"],
  ["Plaster001", "Plaster 001", "plaster", "wall"],
  ["Ground037", "Ground 037", "dirt", "forest", "terrain"],
  ["Concrete034", "Concrete 034", "concrete", "wall"],
  ["Wood051", "Wood 051", "wood"],
  ["Grass001", "Grass 001", "grass", "terrain"],
  ["Grass004", "Grass 004", "grass", "terrain"],
  ["Wood049", "Wood 049", "wood", "furniture"],
  ["WoodFloor051", "Wood Floor 051", "wood", "floor"],
  ["Wood066", "Wood 066", "wood"],
  ["Wood026", "Wood 026", "wood"],
  ["Tiles107", "Tiles 107", "tiles", "floor"],
  ["Wood058", "Wood 058", "wood"],
  ["Marble006", "Marble 006", "marble", "dark"],
  ["Fabric030", "Fabric 030", "fabric"],
  ["Metal032", "Metal 032", "metal"],
  ["PaintedPlaster017", "Painted Plaster 017", "plaster", "wall"],
  ["Wood027", "Wood 027", "wood"],
  ["Concrete031", "Concrete 031", "concrete"],
  ["Metal009", "Metal 009", "metal", "brushed"],
  ["Marble016", "Marble 016", "marble"],
  ["WoodFloor040", "Wood Floor 040", "wood", "floor"],
  ["Wood048", "Wood 048", "wood"],
  ["Metal007", "Metal 007", "metal", "gold"],
  ["Metal046B", "Metal 046 B", "metal", "dark"],
  ["Rock035", "Rock 035", "rock", "cliff"],
  ["Wood060", "Wood 060", "wood"],
  ["WoodFloor043", "Wood Floor 043", "wood", "floor"],
  ["Plaster002", "Plaster 002", "plaster", "wall"],
  ["Ground048", "Ground 048", "dirt", "terrain"],
  ["Marble014", "Marble 014", "marble"],
  ["Fabric019", "Fabric 019", "fabric"],
  ["Wood067", "Wood 067", "wood"],
  ["Wood050", "Wood 050", "wood"],
  ["Marble021", "Marble 021", "marble"],
  ["WoodFloor007", "Wood Floor 007", "wood", "floor"],
  ["WoodFloor041", "Wood Floor 041", "wood", "floor"],
  ["Ground054", "Ground 054", "sand", "beach"],
  ["Bricks075A", "Bricks 075 A", "brick", "wall"],
  ["Concrete030", "Concrete 030", "concrete"],
  ["Fabric036", "Fabric 036", "fabric"],
  ["Tiles040", "Tiles 040", "tiles", "floor"],
  ["Rock020", "Rock 020", "rock"],
  ["Metal011", "Metal 011", "metal"],
  ["Fabric061", "Fabric 061", "fabric"],
  ["Wood028", "Wood 028", "wood"],
  ["Metal034", "Metal 034", "metal", "gold"],
  ["Metal027", "Metal 027", "metal"],
  ["Metal029", "Metal 029", "metal"],
  ["Rock030", "Rock 030", "rock", "cliff"],
  ["Wood092", "Wood 092", "wood"],
  ["Fabric066", "Fabric 066", "fabric"],
  ["Wood062", "Wood 062", "wood"],
  ["Metal012", "Metal 012", "metal"],
  ["Metal038", "Metal 038", "metal", "steel"],
  ["Concrete042A", "Concrete 042 A", "concrete"],
  ["Moss002", "Moss 002", "moss", "nature"],
  ["Wood052", "Wood 052", "wood"],
  ["Bricks060", "Bricks 060", "brick", "wall"],
  ["Wood021", "Wood 021", "wood"],
  ["Bricks066", "Bricks 066", "brick", "wall"],
  ["Wood030", "Wood 030", "wood"],
  ["Tiles074", "Tiles 074", "tiles", "floor"],
  ["Metal035", "Metal 035", "metal", "copper"],
  ["Plastic010", "Plastic 010", "plastic"],
  ["Bricks059", "Bricks 059", "brick", "wall"],
  ["Plastic006", "Plastic 006", "plastic"],
  ["Metal028", "Metal 028", "metal"],
  ["Fabric023", "Fabric 023", "fabric", "carpet"],
  ["Fabric028", "Fabric 028", "fabric", "carpet"],
  ["Tiles078", "Tiles 078", "tiles", "floor"],
  ["Wood006", "Wood 006", "wood"],
  ["Tiles036", "Tiles 036", "tiles", "bathroom"],
  ["Metal036", "Metal 036", "metal"],
  ["Porcelain001", "Porcelain 001", "porcelain"],
  ["Fabric026", "Fabric 026", "fabric", "carpet"],
  ["Carpet016", "Carpet 016", "carpet", "floor"],
  ["Tiles052", "Tiles 052", "tiles", "floor"],
  ["Metal003", "Metal 003", "metal"],
  ["Plaster003", "Plaster 003", "plaster", "wall"],
  ["Grass005", "Grass 005", "grass", "terrain"],
  ["Concrete032", "Concrete 032", "concrete"],
  ["Grass003", "Grass 003", "grass", "terrain"],
  ["Carpet012", "Carpet 012", "carpet", "floor"],
  ["Marble020", "Marble 020", "marble"],
  ["WoodFloor039", "Wood Floor 039", "wood", "floor"],
  ["Concrete036", "Concrete 036", "concrete"],
  ["PavingStones070", "Paving Stones 070", "stone", "path", "outdoor"],
  ["Metal041A", "Metal 041 A", "metal", "iron"],
];

const ACG_HDRIS: [id: string, name: string, ...tags: string[]][] = [
  ["DaySkyHDRI015A", "Day Sky HDRI 015 A", "sky", "day"],
  ["IndoorEnvironmentHDRI005", "Indoor Environment HDRI 005", "indoor", "studio"],
  ["NightSkyHDRI003", "Night Sky HDRI 003", "night", "sky"],
  ["DayEnvironmentHDRI043", "Day Environment HDRI 043", "outdoor", "day"],
  ["DayEnvironmentHDRI004", "Day Environment HDRI 004", "outdoor", "garden"],
  ["IndoorEnvironmentHDRI001", "Indoor Environment HDRI 001", "indoor"],
  ["DaySkyHDRI001A", "Day Sky HDRI 001 A", "sky", "day"],
  ["IndoorEnvironmentHDRI003", "Indoor Environment HDRI 003", "indoor"],
  ["NightSkyHDRI008", "Night Sky HDRI 008", "night", "sky"],
  ["DaySkyHDRI027B", "Day Sky HDRI 027 B", "sky", "clouds"],
  ["DayEnvironmentHDRI057", "Day Environment HDRI 057", "city", "day"],
  ["NightEnvironmentHDRI002", "Night Environment HDRI 002", "city", "night"],
  ["NightEnvironmentHDRI008", "Night Environment HDRI 008", "night", "camp"],
  ["IndoorEnvironmentHDRI013", "Indoor Environment HDRI 013", "indoor"],
  ["DaySkyHDRI012A", "Day Sky HDRI 012 A", "sky", "day"],
  ["DayEnvironmentHDRI052", "Day Environment HDRI 052", "city", "clouds"],
  ["NightSkyHDRI001", "Night Sky HDRI 001", "night", "sky"],
  ["DaySkyHDRI005B", "Day Sky HDRI 005 B", "sky", "clouds"],
  ["DaySkyHDRI012B", "Day Sky HDRI 012 B", "sky", "clouds"],
  ["EveningSkyHDRI005B", "Evening Sky HDRI 005 B", "sunset", "sky"],
  ["NightEnvironmentHDRI001", "Night Environment HDRI 001", "night"],
  ["DaySkyHDRI005A", "Day Sky HDRI 005 A", "sky", "day"],
  ["DaySkyHDRI001B", "Day Sky HDRI 001 B", "sky", "day"],
  ["DaySkyHDRI026A", "Day Sky HDRI 026 A", "sky", "beach"],
  ["DayEnvironmentHDRI003", "Day Environment HDRI 003", "city", "forest"],
];

export const AMBIENTCG_ASSETS: CatalogAsset[] = [
  ...ACG_MATERIALS.map(([id, name, ...tags]) => acgTexture(id, name, tags)),
  ...ACG_HDRIS.map(([id, name, ...tags]) => acgHdri(id, name, tags)),
];

export const KENNEY_AUDIO_EXTRA: CatalogAsset[] = kenneyPack(
  "voiceover-pack-fighter",
  "voiceover-pack-fighter",
  "audio",
  [
    ["kenney_vo_fight_attack", "Voice Attack", "audio", "voice", "combat"],
    ["kenney_vo_fight_hit", "Voice Hit", "audio", "voice", "combat"],
    ["kenney_vo_fight_win", "Voice Win", "audio", "voice"],
    ["kenney_vo_fight_lose", "Voice Lose", "audio", "voice"],
  ],
  { uploadSupported: false },
);
