export type AssetCategory =
  | "prop"
  | "character"
  | "environment"
  | "ui"
  | "audio"
  | "texture";

export type AssetKind = "model" | "image" | "audio" | "texture" | "hdri";

export type CatalogAsset = {
  id: string;
  name: string;
  category: AssetCategory;
  kind: AssetKind;
  tags: string[];
  /** CC0 only until attribution UX unlocks CC-BY. */
  license: "CC0" | "CC-BY";
  attribution: string;
  source: string;
  /** Relative path inside the pack, once downloaded */
  file?: string;
  thumbnail?: string;
  /** Remote URL used by ingest to fetch the binary */
  downloadUrl?: string;
  /** Audio/HDRI may be preview-only */
  uploadSupported: boolean;
  /** Pack id when distributed via GitHub Releases CDN */
  packId?: string;
};

export type AssetCatalog = {
  version: string;
  generatedAt: string;
  description: string;
  assets: CatalogAsset[];
};

export type ProjectAssetEntry = {
  robloxAssetId: string;
  assetType: "Decal" | "Model" | "Image";
  /** For Decals, the image content id if known */
  imageId?: string;
  uploadedAt: string;
  license: "CC0";
  bankId: string;
};

export type ProjectAssetsManifest = {
  templateVersion: string;
  createdWith: string;
  assets: Record<string, ProjectAssetEntry>;
};

export function generateAssetsTs(manifest: ProjectAssetsManifest): string {
  const lines = [
    "/**",
    " * Auto-generated by Blockforge. Do not invent rbxassetid values.",
    " * Re-run asset upload from the app to refresh.",
    " */",
    "export const ASSETS = {",
  ];

  const keys = Object.keys(manifest.assets).sort();
  for (const key of keys) {
    const entry = manifest.assets[key];
    if (!entry) {
      continue;
    }
    const safeKey = key.replace(/[^a-zA-Z0-9_]/g, "_");
    lines.push(`  ${safeKey}: "rbxassetid://${entry.robloxAssetId}",`);
  }

  lines.push("} as const;", "", "export type AssetKey = keyof typeof ASSETS;", "");
  return lines.join("\n");
}
