import { IPC } from "./ipc-types.js";

/** Channels the renderer may invoke via preload. */
export const ALLOWED_INVOKE_CHANNELS: readonly string[] = [
  IPC.PROJECT_LIST,
  IPC.PROJECT_CREATE,
  IPC.PROJECT_OPEN,
  IPC.PROJECT_CLOSE,
  IPC.PROJECT_GET_OPEN,
  IPC.PROJECT_LIST_OPEN,
  IPC.PROJECT_SWITCH,
  IPC.DOCTOR_RUN,
  IPC.DOCTOR_INSTALL_BRIDGE_PLUGIN,
  IPC.PTY_START,
  IPC.PTY_WRITE,
  IPC.PTY_RESIZE,
  IPC.PTY_STOP,
  IPC.PTY_LIST,
  IPC.ROJO_STATUS,
  IPC.ROJO_STOP,
  IPC.ROJO_START,
  IPC.ROJO_RESTART,
  IPC.SETTINGS_GET,
  IPC.SETTINGS_SET,
  IPC.SETTINGS_HAS_API_KEY,
  IPC.PUBLISH_PLACE,
  IPC.ASSET_CATALOG,
  IPC.ASSET_IMPORT,
  IPC.ASSET_LIST_PROJECT,
  IPC.ASSET_PREVIEW,
  IPC.ASSET_PACK_STATUS,
  IPC.ASSET_PACK_DOWNLOAD,
  IPC.ASSET_GENERATE,
  IPC.STYLE_PACK_ACTIVATE,
  IPC.ATTRIBUTION_LIST,
  IPC.MONETIZATION_LIST,
  IPC.MONETIZATION_CREATE,
  IPC.SYNCBACK_STATUS,
  IPC.SYNCBACK_RESOLVE,
  IPC.CLOUD_SYNC_PUSH,
  IPC.CLOUD_SYNC_PULL,
  IPC.COMMUNITY_SHARE,
  IPC.UPDATE_CHECK,
  IPC.UPDATE_DOWNLOAD_INSTALL,
  IPC.APP_INFO,
  IPC.CLIPBOARD_READ,
  IPC.CLIPBOARD_WRITE,
  IPC.GIT_STATUS,
  IPC.GIT_DIFF,
  IPC.GIT_STAGE,
  IPC.GIT_UNSTAGE,
  IPC.GIT_COMMIT,
  IPC.GIT_BRANCHES,
  IPC.GIT_CHECKOUT,
  IPC.GIT_CREATE_BRANCH,
  IPC.GIT_PULL,
  IPC.GIT_PUSH,
  IPC.GIT_DISCARD,
  IPC.BACKUP_CREATE,
  IPC.BACKUP_LIST,
  IPC.BACKUP_RESTORE,
  IPC.ASSET_CHOICE_RESOLVE,
  IPC.ASSET_CHOICE_CANCEL,
  IPC.STUDIO_LOCKS_STATUS,
];

/** Channels the main process may push to the renderer. */
export const ALLOWED_EVENT_CHANNELS: readonly string[] = [
  IPC.PTY_DATA,
  IPC.PTY_EXIT,
  IPC.PTY_STATUS_CHANGED,
  IPC.ROJO_STATUS_CHANGED,
  IPC.ASSET_CHOICE_PENDING,
  IPC.APP_TOAST,
  IPC.OPEN_SETTINGS_FOCUS,
  IPC.STUDIO_LOCKS_CHANGED,
  IPC.PROJECT_CREATE_PROGRESS,
];

export function isAllowedInvokeChannel(channel: string): boolean {
  return ALLOWED_INVOKE_CHANNELS.includes(channel);
}

export function isAllowedEventChannel(channel: string): boolean {
  return ALLOWED_EVENT_CHANNELS.includes(channel);
}
